// components/Footer.vue
<template>
  <footer>
    <div class="container mx-auto px-8 pb-8 text-center">
      <div>&copy; 2020 Aumy</div>
    </div>
  </footer>
</template>

<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";

export default defineComponent({
  name: "Footer",
});
</script>

<style lang="postcss" scoped></style>

// src/components/Footer.tsx
import { css } from "@emotion/react";
import React from "react";

import { container, margin } from "../styles/layout";

export namespace Footer {
  export const Presentation: React.FC = () => {
    return (
      <footer
        css={css`
          ${margin.x("auto")}
          padding: 0 1rem 1rem;
          text-align: center;
          ${container}
        `}
      >
        <small>&copy; 2021 Aumy</small>
      </footer>
    );
  };
}
